---
repo-name: peripherals-oracle
categories:
  - Database
  - Storage
display-name: Oracle
description: Oracle Database is a proprietary multi-model database management system produced and marketed by Oracle Corporation. It is a database commonly used for running online transaction processing, data warehousing and mixed database workloads.
manufacturer: Oracle
product: Oracle
